# ============================
# Etapa 1: Build de Angular
# ============================
	FROM node:18.0.0-alpine3.15 AS build

	WORKDIR /app

    # Copiar package.json y package-lock.json primero (para cache)
    COPY package*.json ./

    #Instalar dependencias como root (permisos completos
    # solo produccion = npm ci --only=production
    # "Limpia archivos temporales para ahorrar espacio" = npm cache clean --force
    RUN npm ci --only=production && npm cache clean --force

    # Ahora copia TODO el código del servidor
    # Usamos un punto (.) para indicar que copie todos los archivos
    # del directorio actual (el contexto de compilación)
    COPY . ./

    # Crear usuario innovatube y grupo nodejs
    # Comando Linux: crear grupo
    RUN addgroup -g 1001 -S nodejs        
     # Comando Linux: crear usuario
    RUN adduser -S innovatube -u 1001    

    # Generar la build de producción
    RUN npm run build --prod


# ============================
# Etapa 2: Servir con Nginx
# ============================
    # Etapa 2: Servir con Nginx
    FROM nginx:1.28-alpine

    # Copiar los archivos compilados de Angular a la carpeta de Nginx
    COPY --from=build /app/dist/innova-tube/browser /usr/share/nginx/html

    # Copiar configuración de Nginx personalizada (opcional)
    COPY nginx.conf /etc/nginx/conf.d/default.conf

    # Exponer el puerto en el que Nginx sirve la app
    EXPOSE 80

    # Comando por defecto
    CMD ["nginx", "-g", "daemon off;"]