// Generated by https://quicktype.io

export interface RegisterResponse {
    id:           string;
    nameCompleto: string;
    nameUser:     string;
    email:        string;
    createdAt:    Date;
    updatedAt:    Date;
}
